log:
  level: DEBUG # INFO normally

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: common

api:
  dashboard: true
  insecure: true   # leave on for local dev; disable in production

entryPoints:
  web:
    address: ":80"

providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true
  docker:
    exposedByDefault: false
    network: demo_net   

experimental:
  plugins:
    jwtValidation:
      moduleName: "github.com/legege/jwt-validation-middleware"
      version: "v0.2.1"
